## Develop a Baseline Neural Network Model

In [212]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from tensorflow.keras import backend as K
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Flatten, BatchNormalization
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_percentage_error
from math import sqrt

In [238]:
def print_scores(y, y_pred):
    rmse = np.sqrt(mean_squared_error(y, y_pred))
    r2 = r2_score(y,y_pred)
    mape = mean_absolute_percentage_error(y, y_pred)
    print('RMSE: ',rmse)
    print('R2: ',r2)
    print('MAPE: ',mape)

In [195]:
df = pd.read_csv('data/prepared_scaled.csv', index_col = 'date')

In [196]:
df.columns

Index(['bank_holiday', 'feature_0', 'feature_1', 'feature_2', 'feature_6',
       'feature_7', 'school_holiday', 'feature_10', 'label', 'air_humidity',
       'air_temperature_daily_max', 'precipitation', 'snow_height',
       'sunshine_hours', 'wind_speed_max', 'month', 'week_day', 'step',
       'trend', 'm_2', 'm_3', 'm_4', 'm_5', 'm_6', 'm_7', 'm_8', 'm_9', 'm_10',
       'm_11', 'm_12', 'd_1', 'd_2'],
      dtype='object')

In [197]:
X = df.drop('label', axis = 1)
y = np.ravel(df['label'])

In [198]:
y.shape

(1743,)

In [199]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [200]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train)

X_train = scaler.transform(X_train)

X_test = scaler.transform(X_test)

In [201]:
X_train

array([[-0.16947163, -0.26762912, -0.23888327, ..., -0.30446121,
         2.39701163, -0.41435099],
       [-0.16947163, -0.26762912, -0.23888327, ..., -0.30446121,
        -0.41718613,  2.41341281],
       [-0.16947163, -0.26762912, -0.23888327, ..., -0.30446121,
        -0.41718613, -0.41435099],
       ...,
       [-0.16947163, -0.26762912, -0.23888327, ..., -0.30446121,
        -0.41718613, -0.41435099],
       [-0.16947163,  3.73651421, -0.23888327, ..., -0.30446121,
        -0.41718613,  2.41341281],
       [-0.16947163, -0.26762912, -0.23888327, ..., -0.30446121,
        -0.41718613, -0.41435099]])

In [241]:
 K.clear_session()

In [242]:
# create base model
model = Sequential()
model.add(Dense(32, input_dim=31, activation='relu'))
model.add(BatchNormalization(momentum=0.99))
model.add(Dense(16, activation='relu'))
model.add(BatchNormalization(momentum=0.99))
model.add(Dense(1))
# Compile model
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [243]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                1024      
_________________________________________________________________
batch_normalization (BatchNo (None, 32)                128       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
batch_normalization_1 (Batch (None, 16)                64        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 17        
Total params: 1,761
Trainable params: 1,665
Non-trainable params: 96
_________________________________________________________________


In [244]:
history = model.fit(
                 X_train,
                 y_train,
                 epochs=100, 
                 batch_size=5, 
                 validation_split=0.3,
                )

Epoch 1/100
164/164 [==============================] - 2s 5ms/step - loss: 1683065.0038 - accuracy: 0.0000e+00 - val_loss: 1759530.6250 - val_accuracy: 0.0000e+00
Epoch 2/100
164/164 [==============================] - 1s 3ms/step - loss: 1567062.0000 - accuracy: 0.0000e+00 - val_loss: 1747764.0000 - val_accuracy: 0.0000e+00
Epoch 3/100
164/164 [==============================] - 0s 3ms/step - loss: 1585159.7098 - accuracy: 0.0000e+00 - val_loss: 1729501.1250 - val_accuracy: 0.0000e+00
Epoch 4/100
164/164 [==============================] - 1s 3ms/step - loss: 1625846.5076 - accuracy: 0.0000e+00 - val_loss: 1705972.1250 - val_accuracy: 0.0000e+00
Epoch 5/100
164/164 [==============================] - 1s 3ms/step - loss: 1750939.6318 - accuracy: 0.0000e+00 - val_loss: 1675147.5000 - val_accuracy: 0.0000e+00
Epoch 6/100
164/164 [==============================] - 1s 5ms/step - loss: 1578497.5394 - accuracy: 0.0000e+00 - val_loss: 1636926.3750 - val_accuracy: 0.0000e+00
Epoch 7/100
164/164 [=

164/164 [==============================] - 0s 3ms/step - loss: 159787.0397 - accuracy: 0.0000e+00 - val_loss: 169366.8281 - val_accuracy: 0.0000e+00
Epoch 52/100
164/164 [==============================] - 0s 3ms/step - loss: 139834.9348 - accuracy: 0.0000e+00 - val_loss: 158957.3125 - val_accuracy: 0.0000e+00
Epoch 53/100
164/164 [==============================] - 0s 3ms/step - loss: 117050.6339 - accuracy: 0.0000e+00 - val_loss: 170887.6094 - val_accuracy: 0.0000e+00
Epoch 54/100
164/164 [==============================] - 0s 3ms/step - loss: 121829.5772 - accuracy: 0.0000e+00 - val_loss: 171901.1094 - val_accuracy: 0.0000e+00
Epoch 55/100
164/164 [==============================] - 0s 3ms/step - loss: 124289.3667 - accuracy: 0.0000e+00 - val_loss: 159292.4375 - val_accuracy: 0.0000e+00
Epoch 56/100
164/164 [==============================] - 1s 4ms/step - loss: 135635.6004 - accuracy: 0.0000e+00 - val_loss: 161339.4375 - val_accuracy: 0.0000e+00
Epoch 57/100
164/164 [===================

In [245]:
test_predictions = model.predict(X_test).flatten().round(0)

In [246]:
train_predictions = model.predict(X_train).flatten().round(0)

In [247]:
test_predictions[:20]

array([1171., 1597., 1266., 1108., 1786.,  783.,  756., 2065., 1922.,
        422., 1275., 1539.,  702.,  729., 1941.,  763.,  792.,  690.,
       3003.,  650.], dtype=float32)

In [248]:
y_test[:20]

array([1340, 1934, 1112, 1200, 2072,  705,  546, 1591, 1977,  785, 1718,
       1199,  659,  621, 2092,  543,  766, 1062, 2707,  590])

In [249]:
print('Test')
print_scores(y_test, test_predictions)
print('Train')
print_scores(y_train, train_predictions)

Test
RMSE:  335.4711756950546
R2:  0.6865301539878872
MAPE:  0.24574589411196118
Train
RMSE:  300.705554212406
R2:  0.7676047900902452
MAPE:  0.21907471629647196
